version: '3'

services:
  backend:
    container_name: backend
    image: filtering-app-backend
    build:
      context: ./backend/filtering-app/
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    restart: always

  ui:
    container_name: ui
    image: filtering-app-ui
    build:
      context: ./ui/filtering-app/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports: 
      - 3000:80
    restart: always
